#!/usr/bin/env python3
"""Generate robots.txt for this static site from its canonical URL."""

from __future__ import annotations

import re
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROBOTS = ROOT / "robots.txt"
NON_PUBLIC_PATHS = ("/.git/", "/docs/", "/node_modules/", "/scripts/", "/screenshots/")


class CanonicalLinkParser(HTMLParser):
    """Extract a canonical URL regardless of the order of link attributes."""

    canonical: str = ""

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag.lower() != "link" or self.canonical:
            return
        data = {name.lower(): value or "" for name, value in attrs}
        if "canonical" in data.get("rel", "").lower().split():
            self.canonical = data.get("href", "")


def site_origin() -> str:
    """Read the production origin from the home page's canonical link."""
    home = (ROOT / "index.html").read_text(encoding="utf-8")
    parser = CanonicalLinkParser()
    parser.feed(home)
    if not parser.canonical.startswith("https://"):
        raise RuntimeError("index.html must have an absolute HTTPS canonical link")
    match = re.match(r"^(https://[^/]+)", parser.canonical)
    if not match:
        raise RuntimeError("index.html canonical link must include a valid HTTPS host")
    return match.group(1)


def main() -> int:
    origin = site_origin()
    disallow = "\n".join(f"Disallow: {path}" for path in NON_PUBLIC_PATHS)
    ROBOTS.write_text(
        "# Generated by scripts/generate-robots.py.\n"
        "# Crawl public pages and assets; repository-only paths are excluded.\n\n"
        "User-agent: *\nAllow: /\n"
        f"{disallow}\n\nSitemap: {origin}/sitemap.xml\n",
        encoding="utf-8",
    )
    print(f"Generated robots.txt for {origin}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
