#!/usr/bin/env python3
"""Generate robots.txt for this static site from its canonical URL."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROBOTS = ROOT / "robots.txt"
CANONICAL_RE = re.compile(r'<link\b[^>]*\brel=["\']canonical["\'][^>]*\bhref=["\']([^"\']+)', re.I)
NON_PUBLIC_PATHS = ("/.git/", "/docs/", "/node_modules/", "/scripts/", "/screenshots/")


def site_origin() -> str:
    """Read the production origin from the home page's canonical link."""
    home = (ROOT / "index.html").read_text(encoding="utf-8")
    match = CANONICAL_RE.search(home)
    if not match or not match.group(1).startswith("https://"):
        raise RuntimeError("index.html must have an absolute HTTPS canonical link")
    return match.group(1).split("/", 3)[:3][0] + "//" + match.group(1).split("/", 3)[2]


def main() -> int:
    origin = site_origin()
    disallow = "\n".join(f"Disallow: {path}" for path in NON_PUBLIC_PATHS)
    ROBOTS.write_text(
        "# Generated by scripts/generate-robots.py.\n"
        "# Crawl public pages and assets; repository-only paths are excluded.\n\n"
        "User-agent: *\nAllow: /\n"
        f"{disallow}\n\nSitemap: {origin}/sitemap.xml\n",
        encoding="utf-8",
    )
    print(f"Generated robots.txt for {origin}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
