import "server-only";

import { mkdir, writeFile } from "fs/promises";
import { join } from "path";

import type { IntakeSelections } from "@/lib/types";

/**
 * Generate WordPress-ready export with theme files
 */
export async function generateWordPressExport(
  html: string,
  projectDir: string,
  intake: IntakeSelections
): Promise<void> {
  // Create WordPress theme structure
  const themeDir = join(projectDir, "wordpress-theme");
  await mkdir(themeDir, { recursive: true });

  // 1. Create functions.php
  const functionsPhp = generateFunctionsPHP(intake);
  await writeFile(join(themeDir, "functions.php"), functionsPhp);

  // 2. Create style.css
  const styleCss = generateStyleCSS(intake);
  await writeFile(join(themeDir, "style.css"), styleCss);

  // 3. Create index.php (main template)
  const indexPhp = generateIndexPHP(html, intake);
  await writeFile(join(themeDir, "index.php"), indexPhp);

  // 4. Create header.php
  const headerPhp = generateHeaderPHP();
  await writeFile(join(themeDir, "header.php"), headerPhp);

  // 5. Create footer.php
  const footerPhp = generateFooterPHP();
  await writeFile(join(themeDir, "footer.php"), footerPhp);

  // 6. Create README for installation
  const readme = generateWordPressReadme(intake);
  await writeFile(join(themeDir, "README.txt"), readme);
}

function generateFunctionsPHP(intake: IntakeSelections): string {
  return `<?php
/**
 * ${intake.companyName} Theme Functions
 * Auto-generated by ash-tra.com
 */

// Add theme support
add_theme_support('post-thumbnails');
add_theme_support('title-tag');
add_theme_support('custom-logo');
add_theme_support('customize-selective-refresh-widgets');

// Enqueue styles
function ${sanitizePhpFunction(intake.companyName)}_enqueue_styles() {
    wp_enqueue_style('${slugifyTheme(intake.companyName)}-style', get_stylesheet_uri());
    wp_enqueue_style('${slugifyTheme(intake.companyName)}-fonts', 'https://fonts.googleapis.com/css2?family=Newsreader:wght@500;700&family=Space+Grotesk:wght@400;500;700&display=swap');
}
add_action('wp_enqueue_scripts', '${sanitizePhpFunction(intake.companyName)}_enqueue_styles');

// Register menus
register_nav_menus(array(
    'primary' => __('Primary Menu', '${slugifyTheme(intake.companyName)}'),
    'footer' => __('Footer Menu', '${slugifyTheme(intake.companyName)}'),
));

// Add custom widgets
function ${sanitizePhpFunction(intake.companyName)}_widgets_init() {
    register_sidebar(array(
        'name' => __('Sidebar', '${slugifyTheme(intake.companyName)}'),
        'id' => 'sidebar',
        'description' => __('Main Sidebar', '${slugifyTheme(intake.companyName)}'),
        'before_widget' => '<div id="%1\\$s" class="widget %2\\$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3 class="widget-title">',
        'after_title' => '</h3>',
    ));
}
add_action('widgets_init', '${sanitizePhpFunction(intake.companyName)}_widgets_init');

// Add custom post types
function ${sanitizePhpFunction(intake.companyName)}_register_post_types() {
    register_post_type('service', array(
        'public' => true,
        'label' => 'Services',
        'supports' => array('title', 'editor', 'thumbnail'),
    ));
}
add_action('init', '${sanitizePhpFunction(intake.companyName)}_register_post_types');
?>`;
}

function generateStyleCSS(intake: IntakeSelections): string {
  return `/*
Theme Name: ${intake.companyName}
Theme URI: https://ash-tra.com
Description: Custom theme auto-generated by ash-tra.com
Version: 1.0.0
Author: ash-tra.com
Text Domain: ${slugifyTheme(intake.companyName)}
Domain Path: /languages
*/

:root {
    --primary-color: #f46036;
    --secondary-color: #10212b;
    --text-color: #10212b;
    --light-bg: #f8f3eb;
    --border-color: rgba(16, 33, 43, 0.12);
}

* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

html, body {
    font-family: 'Space Grotesk', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    font-size: 16px;
    line-height: 1.6;
    color: var(--text-color);
    background: linear-gradient(180deg, #fbf7f1 0%, #f3ecdf 100%);
}

/* Typography */
h1, h2, h3, h4, h5, h6 {
    font-family: 'Newsreader', Georgia, serif;
    font-weight: 700;
    line-height: 1.2;
    margin: 1.5rem 0 0.5rem 0;
}

h1 { font-size: 2.5rem; }
h2 { font-size: 2rem; }
h3 { font-size: 1.5rem; }

p { margin-bottom: 1rem; }

/* Buttons */
button, .button {
    display: inline-block;
    padding: 12px 24px;
    background: var(--primary-color);
    color: white;
    text-decoration: none;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-weight: 600;
    transition: all 0.3s ease;
}

button:hover, .button:hover {
    background: var(--secondary-color);
    transform: translateY(-2px);
}

/* Layout */
.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
}

header {
    padding: 1rem 0;
    background: rgba(255,255,255,0.82);
    box-shadow: 0 2px 4px rgba(0,0,0,0.05);
}

footer {
    background: rgba(255,255,255,0.72);
    padding: 2rem 0;
    margin-top: 4rem;
    color: #666;
}

/* Responsive */
@media (max-width: 768px) {
    h1 { font-size: 1.75rem; }
    h2 { font-size: 1.4rem; }
    h3 { font-size: 1.1rem; }
    
    .container {
        padding: 0 15px;
    }
}
`;
}

function generateIndexPHP(html: string, intake: IntakeSelections): string {
  return `<?php
/**
 * Main template - ${intake.companyName}
 */
get_header();
?>

<main class="container">
    ${html}
</main>

<?php
get_footer();
?>`;
}

function generateHeaderPHP(): string {
  return `<?php
/**
 * Header template
 */
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
    <?php wp_body_open(); ?>
    
    <header>
        <div class="container">
            <div>
                <?php if (has_custom_logo()) {
                    the_custom_logo();
                } else {
                    echo '<h1>' . bloginfo('name') . '</h1>';
                } ?>
            </div>
            <nav>
                <?php wp_nav_menu(array(
                    'theme_location' => 'primary',
                    'container_class' => 'menu-container',
                )); ?>
            </nav>
        </div>
    </header>`;
}

function generateFooterPHP(): string {
  return `<?php
/**
 * Footer template
 */
?>
    <footer>
        <div class="container">
            <div style="text-align: center;">
                <p>&copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?>. All rights reserved.</p>
                <?php wp_nav_menu(array(
                    'theme_location' => 'footer',
                    'container_class' => 'footer-menu',
                )); ?>
            </div>
        </div>
    </footer>

    <?php wp_footer(); ?>
</body>
</html>`;
}

function generateWordPressReadme(intake: IntakeSelections): string {
  return `${intake.companyName} - WordPress Theme
Auto-generated by ash-tra.com

== Installation ==

1. Download the WordPress theme folder
2. Log in to your WordPress admin
3. Go to Appearance > Themes
4. Click "Upload Theme"
5. Select the theme ZIP file
6. Click "Install Now"
7. Click "Activate"

== Features ==

- Mobile-first responsive design
- SEO optimized
- Fast loading
- Customizable with WordPress Customizer
- Built-in support for featured images
- Multiple widget areas

== Support ==

For support, visit https://ash-tra.com

== License ==

This theme is licensed under the GPL.
`;
}

function sanitizePhpFunction(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "");
}

function slugifyTheme(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
